- name: Publish to GPR
  run: |
    ls -la
    ruby -e 'puts Dir["*.gemspec"].inspect'
    gem build omni-nano-command-center.gemspec
    gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
  env:
    GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
    OWNER: ${{ github.repository_owner }}

- name: Publish to RubyGems
  run: |
    ls -la
    ruby -e 'puts Dir["*.gemspec"].inspect'
    gem build omni-nano-command-center.gemspec
    gem push *.gem
  env:
    GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
